a = int(input('nhập số a: '))
b = int(input('nhập số b: '))
print('a + b =',a+b)
print('a - b =',a-b)
print('a * b =',a*b)
print('a / b =',a/b)
print('a ** b =',a**b)
if(a > b): print('a > b')
elif(a < b): print('a < b')
else: print('a = b')
print('a AND b =',a and b)
print('a OR b =',a or b)
print('a XOR b=',a ^ b)
print('NOT a == b =',not a == b)
print('a dịch sang phải một đơn vị =',a >> 1)
print('a dịch sang trái một đơn vi =',a << 1)